ex: ex_compile.c
	gcc ex_compile.c -o ex-compile -I/usr/include/glib-2.0 -I/usr/lib/include -lglib-2.0

wc: word_count.c
	gcc word_count.c -o word_count -I/usr/include/glib-2.0 -I/usr/lib/include -lglib-2.0